### ISSUE TITLE
Boards

### ISSUE THREAD

**Issue by fluppie** [jaccobezemer/Smart-DSMR-P1-Splitter#1]
Hallo @jaccobezemer,

Heb je toevallig een bordje over dat aangekocht kan worden? Of verkoop je eventueel het prototype?
Ik wil een P1 telegram generator gaan maken en dan heb ik ook snelle optocouplers nodig, die kan ik uiteraard gaan bestellen en aan het solderen gaan. Maar als jij deze bordjes kant en klaar hebt liggen, dan kan ik de vraag maar stellen :).

Gr.

Philippe

**Comment by jaccobezemer** [comment]
Hoi Philippe,

Ik heb geen kant en klare printjes liggen. Wel nog een paar onbestukte printplaatjes.
Het prototype bestaat niet meer.

Je zult dus zelf aan de slag moeten.

Met vriendelijke groet,
Jacco

**Comment by fluppie** [comment]
Okidoki, thanks voor de feedback :)
